package rustref

import (
	"os"
	"testing"

	lewpath "github.com/lewtec/lewkit/x/path"
	"github.com/stretchr/testify/require"
)

const sampleLock = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "memchr"
version = "2.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa"

[[package]]
name = "memchr"
version = "2.7.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb"
dependencies = []

[[package]]
name = "my-app"
version = "0.1.0"
dependencies = [
 "memchr 2.7.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_json",
]

[[package]]
name = "serde_json"
version = "1.0.120"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cccc"
`

func TestParseLockfile_VersionUnique(t *testing.T) {
	lf, err := ParseLockfile([]byte(sampleLock))
	require.NoError(t, err)

	v, ok := lf.Version("serde_json")
	require.False(t, !ok || v != "1.0.120",
		"serde_json: got %q ok=%v", v, ok)

	// underscore / hyphen fold
	v, ok = lf.Version("serde-json")
	require.False(t, !ok || v != "1.0.120",
		"serde-json fold: got %q ok=%v", v, ok)

}

func TestParseLockfile_VersionFromRootGraph(t *testing.T) {
	lf, err := ParseLockfile([]byte(sampleLock))
	require.NoError(t, err)

	// Two memchr versions; root my-app pins 2.7.4
	v, ok := lf.Version("memchr")
	require.False(t, !ok || v != "2.7.4",
		"memchr via root: got %q ok=%v want 2.7.4", v, ok)

}

func TestParseLockfile_AmbiguousWithoutRoot(t *testing.T) {
	// No path/workspace package → cannot pick between two versions
	const lock = `
version = 3
[[package]]
name = "foo"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
[[package]]
name = "foo"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`
	lf, err := ParseLockfile([]byte(lock))
	require.NoError(t, err)

	_, ok := lf.Version("foo")
	require.False(t, ok,
		"expected ambiguous foo to fail")

}

func TestFindLockfile(t *testing.T) {
	dir := t.TempDir()
	sub := lewpath.New(dir, "src", "bin").String()
	{
		err := os.MkdirAll(sub, 0o755)
		require.NoError(t, err)
	}
	{

		err := os.WriteFile(lewpath.New(dir, "Cargo.lock").String(), []byte(sampleLock), 0o644)
		require.NoError(t, err)
	}

	path, lf, err := FindLockfile(sub)
	require.NoError(t, err)
	require.False(t, path == "" || lf == nil,
		"expected lockfile")

	v, ok := lf.Version("memchr")
	require.False(t, !ok || v != "2.7.4",
		"memchr: %q ok=%v", v, ok)

}

func TestLockPackage_DirName(t *testing.T) {
	p := LockPackage{Name: "memchr", Version: "2.7.4"}
	g := p.DirName()
	require.Equal(t, "memchr-2.7.4", g,
		"DirName=%q", g)

}

func TestParseDepSpec(t *testing.T) {
	cases := []struct {
		in, name, ver string
	}{
		{"memchr", "memchr", ""},
		{"memchr 2.7.4", "memchr", "2.7.4"},
		{"memchr 2.7.4 (registry+https://github.com/rust-lang/crates.io-index)", "memchr", "2.7.4"},
	}
	for _, tc := range cases {
		n, v, ok := parseDepSpec(tc.in)
		require.False(t, !ok || n != tc.name || v != tc.ver,
			"%q → %q %q ok=%v", tc.in, n, v, ok)

	}
}
